version: "3.7"

services:
  backend:
    image: node:lts
    volumes:
      - "./backend/package.json:/usr/app/backend/package.json"
      - "./backend/package-lock.json:/usr/app/backend/package-lock.json"
      - "./backend/tsconfig.json:/usr/app/backend/tsconfig.json"
      - "./backend/tsconfig.build.json:/usr/app/backend/tsconfig.build.json"
      - "./.env:/usr/app/.env"
      - "./backend/src:/usr/app/backend/src"
    working_dir: /usr/app/backend
    command: bash -c "npm install && npm run start:dev"
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:12
    env_file:
      - .env

  redis:
    image: "redis:6"
    env_file:
      - .env
